USE TSQL2012;
IF OBJECT_ID('dbo.SKU', 'U') IS NOT NULL DROP TABLE dbo.SKU;
IF OBJECT_ID('dbo.Family', 'U') IS NOT NULL DROP TABLE dbo.Family;
IF OBJECT_ID('dbo.Basket', 'U') IS NOT NULL DROP TABLE dbo.Basket;

CREATE TABLE dbo.SKU
(
ID INT NOT NULL IDENTITY,
CONSTRAINT PR_SKU PRIMARY KEY(ID),
Name NVARCHAR(40) 
);

CREATE TABLE dbo.Family
(
ID INT NOT NULL IDENTITY,
CONSTRAINT PR_Family PRIMARY KEY(ID),
SurName NVARCHAR(40),
BudgetValue INT
);

CREATE TABLE dbo.Basket
(
ID INT NOT NULL IDENTITY,
ID_SKU INT,
ID_Family INT,
CONSTRAINT FK_BASKET_SKU FOREIGN KEY(ID_SKU) REFERENCES dbo.SKU (ID),
CONSTRAINT FK_BASKET_Family FOREIGN KEY(ID_Family) REFERENCES dbo.Family (ID),
Quantity INT, 
Value INT, 
CHECK (Quantity >= 0),
CHECK (Value >= 0),
PurchaseDate DATE DEFAULT(SYSDATETIME()), 
DiscountValue INT
);